// ESM wrapper for @zentrix/baileys
// Supports: import { makeWASocket } from '@zentrix/baileys'
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const baileys = require('./index.js');

export const makeWASocket = baileys.makeWASocket || baileys.default;
export const useMultiFileAuthState = baileys.useMultiFileAuthState;
export const DisconnectReason = baileys.DisconnectReason;
export const fetchLatestBaileysVersion = baileys.fetchLatestBaileysVersion;
export const fetchLatestWaWebVersion = baileys.fetchLatestWaWebVersion;
export const makeCacheableSignalKeyStore = baileys.makeCacheableSignalKeyStore;
export const makeInMemoryStore = baileys.makeInMemoryStore;
export const getContentType = baileys.getContentType;
export const downloadContentFromMessage = baileys.downloadContentFromMessage;
export const downloadMediaMessage = baileys.downloadMediaMessage;
export const generateWAMessage = baileys.generateWAMessage;
export const generateWAMessageFromContent = baileys.generateWAMessageFromContent;
export const generateWAMessageContent = baileys.generateWAMessageContent;
export const prepareWAMessageMedia = baileys.prepareWAMessageMedia;
export const areJidsSameUser = baileys.areJidsSameUser;
export const isJidBroadcast = baileys.isJidBroadcast;
export const isJidGroup = baileys.isJidGroup;
export const isJidUser = baileys.isJidUser;
export const isJidNewsletter = baileys.isJidNewsletter;
export const jidDecode = baileys.jidDecode;
export const jidNormalizedUser = baileys.jidNormalizedUser;
export const jidEncode = baileys.jidEncode;
export const Browsers = baileys.Browsers;
export const BufferJSON = baileys.BufferJSON;
export const WAProto = baileys.WAProto;
export const proto = baileys.proto;
export const initAuthCreds = baileys.initAuthCreds;
export const getBinaryNodeChild = baileys.getBinaryNodeChild;
export const getBinaryNodeChildren = baileys.getBinaryNodeChildren;
export const getAllBinaryNodeChildren = baileys.getAllBinaryNodeChildren;
export const encodeBigEndian = baileys.encodeBigEndian;
export const toNumber = baileys.toNumber;
export const generateMessageID = baileys.generateMessageID;
export const generateMessageIDV2 = baileys.generateMessageIDV2;
export const getDevice = baileys.getDevice;
export const isWABusinessPlatform = baileys.isWABusinessPlatform;
export const makeMutex = baileys.makeMutex;
export const makeOrderedDictionary = baileys.makeOrderedDictionary;
export const extractMessageContent = baileys.extractMessageContent;
export const normalizeMessageContent = baileys.normalizeMessageContent;
export const generateForwardMessageContent = baileys.generateForwardMessageContent;
export const generateThumbnail = baileys.generateThumbnail;
export const getUrlFromDirectPath = baileys.getUrlFromDirectPath;
export const MediaType = baileys.MediaType;
export const MessageType = baileys.MessageType;
export const Mimetype = baileys.Mimetype;
export const MimetypeMap = baileys.MimetypeMap;
export const WAMessageStatus = baileys.WAMessageStatus;
export const WAMessageStubType = baileys.WAMessageStubType;
export const WA_DEFAULT_EPHEMERAL = baileys.WA_DEFAULT_EPHEMERAL;
export const STORIES_JID = baileys.STORIES_JID;
export const S_WHATSAPP_NET = baileys.S_WHATSAPP_NET;
export const OFFICIAL_BIZ_JID = baileys.OFFICIAL_BIZ_JID;

export default makeWASocket;
